// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp18UBbtPrP8o76Pd9O_LOXDti8pAGXK4',
    appId: '1:79972934725:android:7eb820dbbe1e1280122f2c',
    messagingSenderId: '79972934725',
    projectId: 'pizzapredator-a445e',
    storageBucket: 'pizzapredator-a445e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0UHJ0K6iZ_8KFcuc4qbOqRePRAZMOrmo',
    appId: '1:79972934725:ios:f89acd9c23fc7757122f2c',
    messagingSenderId: '79972934725',
    projectId: 'pizzapredator-a445e',
    storageBucket: 'pizzapredator-a445e.firebasestorage.app',
    androidClientId: '79972934725-imtfd259pkft9n1ro6b2063qkjo8ttjf.apps.googleusercontent.com',
    iosClientId: '79972934725-jc81fq6kgkgmphcb3end1q7ff017p3lb.apps.googleusercontent.com',
    iosBundleId: 'com.pizzapredator.bikesPizza',
  );
}
