import 'dart:async';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

/// The launch screen: the logo and "bikes.pizza" wordmark on the icon's
/// teal. It is the same artwork the native launch screens draw (Android's
/// launch_background / Android 12 splash icon and iOS's LaunchScreen
/// storyboard, all generated by tool/splash/render_splash.py), so the
/// hand-over from the operating system's splash to Flutter is seamless.
class SplashScreen extends StatelessWidget {
  const SplashScreen({super.key});

  static const teal = Color(0xFF80C6C4);

  /// The artwork's width as a fraction of the screen's shorter side: the
  /// wordmark spans 80% of the width in portrait and keeps exactly that
  /// size in landscape, so the logo is the same size either way.
  static const widthFraction = 0.8;

  static const asset = 'assets/splash/splash.png';

  /// Decodes the artwork so the first frame can draw it.
  static Future<void> warmUp(BuildContext context) =>
      precacheImage(const AssetImage(asset), context);

  @override
  Widget build(BuildContext context) {
    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: SystemUiOverlayStyle.dark,
      child: ColoredBox(
        color: teal,
        child: LayoutBuilder(
          builder: (context, constraints) {
            final side = math.min(constraints.maxWidth, constraints.maxHeight);
            return Center(
              child: Image.asset(
                asset,
                key: const Key('splash-art'),
                width: widthFraction * side,
                excludeFromSemantics: true,
              ),
            );
          },
        ),
      ),
    );
  }
}

/// Shows the [SplashScreen] while [load] builds the app, then fades the app
/// in over it.
///
/// The first frame is held back until [warmUp] has decoded the splash
/// artwork, so the native splash screen stays up until Flutter can draw the
/// same picture; the splash then stays for at least [minimum], counted from
/// that first frame rather than from process start (engine start-up can take
/// a second or more in debug builds, and the wordmark should still be seen).
class AppBootstrap extends StatefulWidget {
  const AppBootstrap({
    super.key,
    required this.load,
    this.minimum = const Duration(milliseconds: 1200),
    this.fade = const Duration(milliseconds: 400),
    this.warmUp = SplashScreen.warmUp,
    this.warmUpLimit = const Duration(seconds: 2),
  });

  final Future<Widget> Function() load;
  final Duration minimum;
  final Duration fade;

  /// Prepares whatever the splash needs before the first frame is released;
  /// the frame is released anyway after [warmUpLimit].
  final Future<void> Function(BuildContext context) warmUp;
  final Duration warmUpLimit;

  @override
  State<AppBootstrap> createState() => _AppBootstrapState();
}

class _AppBootstrapState extends State<AppBootstrap> {
  Widget? _app;
  bool _warmingUp = false;
  final _firstFrame = Completer<void>();

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.deferFirstFrame();
    _start();
  }

  Future<void> _start() async {
    final results = await Future.wait<Object?>([
      widget.load().then<Object?>((app) => app, onError: (Object e) => e),
      _firstFrame.future.then((_) => Future<void>.delayed(widget.minimum)),
    ]);
    if (!mounted) return;
    final result = results.first;
    setState(() {
      _app = result is Widget ? result : _StartupError(error: result!);
    });
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    if (_warmingUp) return;
    _warmingUp = true;
    widget
        .warmUp(context)
        .timeout(widget.warmUpLimit, onTimeout: () {})
        .whenComplete(_releaseFrame);
  }

  void _releaseFrame() {
    if (_firstFrame.isCompleted) return;
    _firstFrame.complete();
    WidgetsBinding.instance.allowFirstFrame();
  }

  @override
  void dispose() {
    _releaseFrame();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    // The app fades in on top of the splash, which stays fully opaque
    // underneath until the switcher drops it: no dip to the window color.
    return AnimatedSwitcher(
      duration: widget.fade,
      transitionBuilder: (child, animation) => child is SplashScreen
          ? child
          : FadeTransition(opacity: animation, child: child),
      child: _app ?? const SplashScreen(),
    );
  }
}

class _StartupError extends StatelessWidget {
  const _StartupError({required this.error});

  final Object error;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Text('bikes.pizza could not start.\n\n$error'),
          ),
        ),
      ),
    );
  }
}
